name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04-x64  # Ensure this matches your self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Ruby is Installed (For Self-Hosted Runners)
        run: |
          RUBY_VERSION=3.2.2
          INSTALL_DIR=/opt/hostedtoolcache/Ruby/$RUBY_VERSION/x64
          COMPLETE_FILE="$INSTALL_DIR.complete"

          if [ ! -f "$COMPLETE_FILE" ]; then
            echo "Installing Ruby $RUBY_VERSION..."
            mkdir -p $INSTALL_DIR
            ruby-build $RUBY_VERSION $INSTALL_DIR
            touch $COMPLETE_FILE
          else
            echo "Ruby $RUBY_VERSION is already installed."
          fi

      - name: Setup Ruby Environment
        run: |
          RUBY_VERSION=3.2.2
          INSTALL_DIR=/opt/hostedtoolcache/Ruby/$RUBY_VERSION/x64
          echo "Adding Ruby to PATH"
          echo "$INSTALL_DIR/bin" >> $GITHUB_PATH
          ruby -v

      - name: Setup Bundler
        run: |
          gem install bundler
          bundle install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
